---
title: "LA_Crime_Mapping"
author: "Shivani Sickotra"
date: "17/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r include=FALSE}
# Load Packages
library(sf) # simple features spatial data
library(ggplot2)
library(dplyr) # to filter dataframes
library(RColorBrewer) # for diverging colour scheme
library(tidyverse) # for piping
library(ggmap)
library(ggsn) # for north and scale bar
library(png) # for inset map
library(ggpubr) # for multi plots
library(cowplot) #multiplot
library(magick) #for adding image
#library(maptools)
#library(mapproj)
```

## Import the LA Shapefile Data
```{r}
#Import LA Shapefile using st_read 
LA<-st_read("Geo_Vis_2_Data/LA_County_City_Boundaries/LA_County_City_Boundaries.shp",            stringsAsFactors=FALSE)

#Check CRS of the LA shapefile
#st_crs(LA)  # CRS is WGS 84, EPSG 4326
#View(LA) #opens the 'attribute' table in the Editor window for viewing

#LA_city<-st_read("Geo_Vis_2_Data/City_Boundary/City_Boundary.shp")
# get bounding box coords of LA 
#LA_city.bbox<-st_bbox(LA_city)

```


## Import the LA Crime Data
```{r}
# https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8
# to present is 15/12/21
LAcrime <- read.csv("Geo_Vis_2_Data/LA_Crime_Data_from_2020_to_Present.csv")

#View the imported dataframe
# Each observation/row is a crime incident that has occured
#View(LAcrime)  # Open attribute table, 390,356 obs with 28 variables
#str(LAcrime) # see datatypes of each column 

```

```{r}
# Deal with missing coord data in the LAcrime dataframe
# Select the observations where LON does NOT have 0 values OR LAT does NOT have 0 values
LAcrime<- LAcrime %>% 
              filter(LON != 0
                     | LAT != 0)   # remaining 387,999 obs

```



## Filter City of LA and plot the boundary

```{r}
 
# Plot only the City of LA boundary from the LA county
# Use filter from dplyr to select only the City of Los Angeles area
LA_city <- filter(LA, CITY_LABEL == "Los Angeles")
```
```{r}
#st_geometry_type(LA_city)
```


```{r}
# get bounding box coords of LA 
LA_city.bbox<-st_bbox(LA_city)
```
```{r}
# Plot the City of Los Angeles geometry using ggplot
ggplot() +
  geom_sf(data=LA_city) +
  # Add the crime point data +
  #geom_point(data=LAcrime, mapping = aes(x=LON, y=LAT), color="red") +
  geom_hex(data=LAcrime,
           mapping = aes(x=LON, y=LAT), bins=15, color="black")+
  #scale_fill_continuous(type = "viridis")
  scale_fill_fermenter(n.breaks=10,palette = "RdYlBu")

```
```{r}
# Plot the City of Los Angeles geometry using ggplot
ggplot() +
  #geom_sf(data=LA_city) +
  # Add the crime point data +
  #geom_point(data=LAcrime, mapping = aes(x=LON, y=LAT), color="red") +
  geom_bin_2d(data=LAcrime,
           mapping = aes(x=LON, y=LAT));

```
```{r}
# Plot the City of Los Angeles geometry using ggplot
ggplot(data=LAcrime, aes(x=LON, y=LAT)) +
  #geom_sf(data=LA_city) +
  # Add the crime point data +
  #geom_point(data=LAcrime, mapping = aes(x=LON, y=LAT), color="red") +
  geom_density_2d_filled()

```
```{r}
# Plot the City of Los Angeles geometry using ggplot
ggplot() +
  geom_sf(data=LA_city) +
  # Add the crime point data +
  #geom_point(data=LAcrime, mapping = aes(x=LON, y=LAT), color="red") +
  geom_density_2d(data=LAcrime,
           mapping = aes(x=LON, y=LAT));
  
```

```{r}
# Plot the City of Los Angeles geometry using ggplot
ggplot() +
  geom_sf(data=LA_city) +
  # Add the crime point data +
  #geom_point(data=LAcrime, mapping = aes(x=LON, y=LAT), color="red") +

  stat_density_2d(data=LAcrime, geom = "polygon", contour = TRUE,
                    aes(x=LON, y=LAT, fill = after_stat(level)), colour = "black",
                    bins = 10) +
  scale_fill_distiller(palette = "RdYlBu", direction = -1) +
  theme_classic();
```



## TYPE of crime 
```{r}
# Understand the crime categories for the incidents
# Find all unique values for the Crm.Cd.Desc variable
unique(LAcrime[c("Crm.Cd.Desc")])   # 135 different categories of crime
```
```{r}
# Get count of each type of crime 
LAcrime %>% count(Crm.Cd.Desc, sort = TRUE)

#SHOPLIFTING - PETTY THEFT ($950 & UNDER) = 6197 counts
# SHOPLIFTING-GRAND THEFT ($950.01 & OVER) = 1093 counts
# Total Shoplifting  = 7290
count(filter(LAcrime, Crm.Cd.Desc == "SHOPLIFTING - PETTY THEFT ($950 & UNDER)"))  #Petty theft/shoplifting = 1093
```


```{r include=FALSE}
# Get Basemap from online and use LA_City bounding box to contrain this
LA_bmap <- get_map(location = c(left = LA_city.bbox[[1]],
                                bottom =LA_city.bbox[[2]],
                                right = LA_city.bbox[[3]],
                                top = LA_city.bbox[[4]]),
                   source="osm")
```



```{r}
# ONLY MAPPING SHOPLIFTING GRAND AND PETTY
map2<- ggmap(LA_bmap) +   #use the LA OSM basemap
       
  # 2d kernel density estimation and display result with contours - to prevent overplotting of points
       stat_density_2d(data= filter(LAcrime, Crm.Cd.Desc == "SHOPLIFTING-GRAND THEFT ($950.01 & OVER)" | Crm.Cd.Desc =="SHOPLIFTING - PETTY THEFT ($950 & UNDER)"),
                       geom = "polygon",
                       contour = TRUE,
                       aes(x=LON, y=LAT,
                           fill = after_stat(level)),
                       alpha = 0.4,
                       colour = "darkblue",
                       bins= 6) +
       scale_fill_distiller(palette = "RdYlBu", direction = -1,
                            breaks = c(10, 15, 20, 25, 30),
                            labels = c("Low","","Med","","High"),
                            name = "Density") +
      #no axis 
       theme_void() +
       ggtitle("Shoplifting Incidents (n = 7290)") +
       theme(legend.position = "none",
             #legend.title = element_text(size=10, face="bold"),
             #legend.key.size = unit(0.5, "cm"),
             plot.title = element_text(size=10, face="bold",hjust = 0.5, vjust= 1.5),
              plot.margin = rep(unit(0,"null"),4),
              panel.margin = unit(0,"null"))
        
      
     
      

map2
```
# ALL crimes map
```{r}
# Plot the City of Los Angeles geometry using ggplot
map1<- ggplot() +
  geom_sf(data=LA_city) +
  
  stat_density_2d(data=LAcrime, geom = "polygon", contour = TRUE,
                    aes(x=LON, y=LAT, fill = after_stat(level)),
                  alpha = 0.6,
                  colour = "darkblue",
                  
                    bins = 5) +
  scale_fill_distiller(palette = "RdYlBu", direction = -1,
                       breaks = c(20, 30, 40, 50, 60),
                            labels = c("Low","","Med","","High"),
                            name = "Density") +
  theme_void() +
  ggtitle("All Crime Incidents (n = 387,999)")+
  theme(legend.position = c(0.10, 0.25),
             legend.title = element_text(size=8),
             legend.key.size = unit(0.3, "cm"),
             plot.title = element_text(size=10, face="bold",hjust = 0.5, vjust= 1.5),
         plot.margin = rep(unit(0,"null"),4),
        panel.spacing = unit(0,"null"))
```

# Inset map
```{r}
# https://nsholmes21.medium.com/the-puzzle-of-places-in-la-18e8a537e3ac
#inset <- readPNG("Geo_Vis_2_Data/LA_inset_map.png")
#inset

inset <- image_read("LA_inset_map.png")
# Resize
inset<-image_scale(inset, "122x100") # width: 300px
```
# Arrange on one page
```{r}
Map3<-ggarrange(
  ggarrange(NULL, map1, nrow = 2, heights=c(0.5,1)),
  map2,
  ncol= 3)

annotate_figure(Map3,
                top = text_grob("Crime Incidents and Shoplifting Density \nin the City of Los Angeles, California 2020/21", hjust=0.8,face = "bold", size = 14),
                bottom = text_grob("Crime Data from data.lacity.org and Boundary Data from geohub.lacity.org. Created by Shivani Sickotra, December 2021", hjust=0.8, face = "italic",
                                   size = 6))

```
```{r}
ggdraw()
#sets up a new coordinate system running from 0 to 1. This
# allows you to place an image on top of the plot.
Map4<-ggdraw(Map3) + 
  draw_image("LA_inset_map.png", scale=0.25, hjust=0.38, vjust=-0.3)

annotate_figure(Map4,
                top = text_grob("Crime Incidents and Shoplifting Density \nin the City of Los Angeles, California 2020/21", hjust=0.8,face = "bold", size = 14),
                centre = text_grob("City of LA, CA, USA", size = 8, face="italic"),
                bottom = text_grob("Crime Data from data.lacity.org and Boundary Data from geohub.lacity.org. Created by Shivani Sickotra, December 2021", hjust=0.8, face = "italic",
                                   size = 6))
```


